---
- name: Download k3s binary
  get_url:
    url: "{{ ansible_k3s_bin_url }}"
    dest: "{{ ansible_k3s_bin_path }}"
    checksum: "{{ ansible_k3s_vars_k3s_matrix[ansible_k3s_version] }}"
    mode: 0755
    owner: root
    group: root

- name: Symlink k3s binary to unversioned binary name
  file:
    src: "{{ ansible_k3s_bin_path }}"
    dest: "{{ ansible_k3s_bin_base_path }}/k3s"
    owner: root
    group: root
    state: link
