---
- name: Disable K3s
  systemd:
    name: k3s
    state: stopped
    enabled: no
  failed_when: false

- name: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  register: pkill_containerd_shim_runc
  command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  changed_when: "pkill_containerd_shim_runc.rc == 0"
  failed_when: false

- name: Umount k3s filesystems
  include_tasks: umount.yml
  with_items:
    - /run/k3s
    - /var/lib/kubelet
    - /run/netns
    - /var/lib/rancher/k3s
  loop_control:
    loop_var: mounted_fs

- name: Remove service files, binaries and data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/k3s.service
    - /etc/systemd/system/k3s.service.env
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s
    - /var/lib/kubelet
    - /usr/local/bin/k3s
    - "/usr/local/bin/k3s-{{ ansible_k3s_version }}"
    - /usr/local/bin/kubectl
    - /usr/local/bin/crictl

- name: daemon_reload
  systemd:
    daemon_reload: yes
