---
- name: Prepare apt cache
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

- name: Prepare roles
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.buildtools
    - role: robertdebock.epel
    - role: hyperfocus1337.python_pip
